/* Generated by tools/mkassets.py: do not edit. */
#ifndef ASSETS_H
#define ASSETS_H
#include <stdint.h>

#define ART_CW 35
#define ART_CH 47
#define ART_NSPRITES 385
#define ART_NGROUPS 6
#define ART_TMPL_JOKER 0
#define ART_TMPL_CONS 157
#define ART_TMPL_VOUCH 211
#define ART_G_JOKER 0
#define ART_G_CONS 1
#define ART_G_VOUCH 2
#define ART_G_DECK 3
#define ART_G_MISC 4
#define ART_G_LOGO 5
#define SPR_TMPL_JOKER 0
#define SPR_J 1
#define SPR_JSOUL 151
#define SPR_TMPL_CONS 157
#define SPR_C 158
#define SPR_SOULGEM 210
#define SPR_TMPL_VOUCH 211
#define SPR_V 212
#define SPR_P 244
#define SPR_E 259
#define SPR_SEAL 269
#define SPR_DEBUFF 273
#define SPR_F 274
#define SPR_B 326
#define SPR_T 357
#define SPR_SHOP 381
#define SPR_STAKE 382
#define SPR_CHIP 383
#define SPR_LOGO 384
typedef struct { uint32_t off : 24, group : 8; uint8_t w, h; } art_sprite_t;
extern const art_sprite_t art_sprites[ART_NSPRITES];
extern const uint8_t art_blob[];
extern const uint16_t art_pal[]; /* the groups' palettes, one after the other */
extern const uint16_t art_pal_off[ART_NGROUPS];
extern const int16_t art_tmpl_of_group[ART_NGROUPS];
typedef struct { uint16_t off; uint8_t w, adv; } glyph_t;
#define FONT_SMALL_H 9
#define FONT_MED_H 12
#define FONT_LARGE_H 14
extern const glyph_t font_small[99], font_med[95], font_large[95], font_large_digits[10];
extern const uint8_t font_small_bits[], font_med_bits[], font_large_bits[], font_large_digits_bits[];
#endif
