#!/usr/bin/env python3
"""Turns games/games.json into make variables (order, screenshots)."""
import json
import sys

games = json.load(open(sys.argv[1]))
print("# Generated by tools/games_mk.py from games/games.json")
print("GAMES := " + " ".join(g["id"] for g in games))
for n, g in enumerate(games, 1):
    i = g["id"]
    print(f"INDEX_{i} := {n}")
    print(f"SHOTS_{i} := " + " ".join(f"games/{i}/{s}" for s in g["shots"]))
    print(f"SHOTS_REL_{i} := " + " ".join(g["shots"]))
    if g.get("colors"):
        print(f"COLORS_{i} := --colors {g['colors']}")
