/* NumPlay launcher: shared definitions. */
#ifndef NP_H
#define NP_H
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

typedef uint16_t color_t;
#define RGB(r, g, b) ((color_t)((((r) & 0xF8) << 8) | (((g) & 0xFC) << 3) | ((b) >> 3)))
#define HEX(v) RGB(((v) >> 16) & 0xFF, ((v) >> 8) & 0xFF, (v) & 0xFF)
#define SCREEN_W 320
#define SCREEN_H 240
#define NP_MIN(a, b) ((a) < (b) ? (a) : (b))
#define NP_MAX(a, b) ((a) > (b) ? (a) : (b))
#define NP_CLAMP(v, lo, hi) ((v) < (lo) ? (lo) : (v) > (hi) ? (hi) : (v))

/* Keys, independent of the calculator's numbering. The number pad doubles
 * as arrows (8 4 6 2) and 5 as OK. */
enum {
  K_LEFT = 1, K_RIGHT = 2, K_UP = 4, K_DOWN = 8, K_OK = 16, K_BACK = 32, K_HOME = 64, K_BACKSPACE = 128
};

/* ---- platform (platform.c) */
uint32_t np_keys(void);           /* keys held right now */
uint32_t np_millis(void);
void np_sleep(unsigned ms);
void np_vblank(void);
void np_push(int x, int y, int w, int h, const color_t *px);
void np_fill_screen(int x, int y, int w, int h, color_t c);
/* Waits until every key is released (after a game, or before quitting). */
void np_wait_release(void);

/* ---- one arena for everything big: the running game's RAM, or the
 * launcher's buffers while no game runs */
extern uint8_t np_arena[];
extern const uint32_t np_arena_size;
void *np_alloc(uint32_t size);    /* bump allocator in the arena */
void np_alloc_reset(void);

/* ---- games (games.c, table generated by tools/gen_games.py) */
typedef struct {
  uint16_t w, h, ncolors;
  uint32_t zsize;
  const color_t *palette;
  const uint8_t *z;             /* raw DEFLATE of w*h palette indices */
} np_shot_t;

typedef struct {
  const char *id, *title, *tagline, *credit;
  uint32_t top, bottom, accent;          /* 0xRRGGBB theme colours */
  const uint32_t *begin, *end;           /* the game's block of flash */
  int (*main)(void);
  uint8_t *data;                         /* the game's RAM inside the arena */
  const uint8_t *data_init;
  uint32_t data_size;
  uint8_t *bss;
  uint32_t bss_size;
  const np_shot_t *shots;
  uint8_t nshots;
  const char *const *records;            /* save files, deleted on uninstall */
  uint32_t est_size;                     /* code and data, for the simulator */
} np_game_t;

extern const np_game_t np_games[];
extern const int np_game_count;

bool np_game_installed(int i);
uint32_t np_game_size(int i);            /* bytes of flash */
void np_game_run(int i);

/* ---- storage (storage.c): Epsilon's record file system */
bool np_storage_delete(const char *name);   /* true if gone (or never there) */
uint32_t np_storage_record_size(const char *name);

/* ---- uninstalling (flash.c) */
enum { NP_UNINSTALL_OK, NP_UNINSTALL_UNSUPPORTED, NP_UNINSTALL_BATTERY, NP_UNINSTALL_FAILED };
bool np_uninstall_supported(void);
bool np_battery_ok(void);
int np_uninstall(int game, void (*progress)(int done, int total));
void np_finish_pending_uninstalls(void);

/* ---- the screens (home.c, settings.c) */
int np_home(int *selected);              /* returns a game index, -1 for settings, -2 to quit */
void np_settings(void);

#endif
